### ISSUE TITLE
Add auth for jenkins

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/devspace#41]
Rather than using the jenkins admin capabilities, it'd may be simpler to use nginx to configure a user.

**Comment by aleksandra-tarkowska** [comment]
the problem with nginx basic auth is that Jenkins will be completely hidden behind password. It turned out that is easier to do:
- Security Realm, choose LDAP. Once you add config, try to log in as yourself before you go to the next step. Otherwise you may lock Jenkins.
- Authorization, choose Logged-in users can do anything 
In order to add ssl the easiest was tu use nginx container to proxypass to jetty

**Comment by aleksandra-tarkowska** [comment]
see https://github.com/openmicroscopy/devspace/pull/31

**Comment by joshmoore** [comment]
Thanks, @aleksandra-tarkowska
